version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: shared_text_editor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 